json.id favorite.id
json.user_id favorite.user_id
json.brewery_id favorite.brewery_id
json.name favorite.name
json.city favorite.city
json.state favorite.state
json.brewery_type favorite.brewery_type
json.website_url favorite.website_url
json.image_url favorite.image_url
json.longitude favorite.longitude
json.latitude favorite.latitude
json.address favorite.address